### READ Order
GET http://localhost:1337/api/orders

### READ Transaction
GET http://localhost:1337/api/transactions

### CREATE Transaction
POST http://localhost:1337/api/transactions
Content-Type: application/json

{
    "data": {
        "transaction_id": "1234",
        "products": {
            "id": 1,
            "name": "tes products trans"
        }
    }
    
}